### ISSUE TITLE
1.29 support ?

### ISSUE THREAD

**Issue by albert-kam** [FooleAU/wc3proxy#8]
Hi, does it support 1.29 version ? My binary wc3proxy currently supports until 1.28 only, which is unfortunate considering the widescreen support from 1.29.

Thanks !

**Comment by FooleAU** [comment]
Nope, sorry.  I'll see if I can fix that up soon.

**Comment by albert-kam** [comment]
Thank you, cannot wait. Currently had to settle with 1.27, the wide screen version, lol.

**Comment by FooleAU** [comment]
Please try [v1.6](https://github.com/FooleAU/wc3proxy/releases/tag/v1.6) and let me know if it works ok.

**Comment by albert-kam** [comment]
It totally works ! Thank you so much.
